config/routes.rb
Rails.application.routes.draw do

  resources :recipes

  get '/search' => 'recipes#search'

  root :to => 'pages#home'

  resources :users, :only => [:index, :new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :myfoods
  delete '/myfoods/:myfood_id/recipes/:recipe_id' => 'myfoods#remove_recipe', :as => 'remove_recipe'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/myfood.rb
class Myfood < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :recipes, dependent: :destroy

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :myfoods
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :presence => true, :uniqueness => true
  has_secure_password
  has_many :myfoods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to login_path unless (@current_user.present? && @current_user.admin?)
  end

end

app/controllers/myfoods_controller.rb
class MyfoodsController < ApplicationController
  before_action :check_for_login

  def index
    @myfoods = Myfood.all
  end


  def new
    @myfood = Myfood.new
  end

  def create
    myfood = Myfood.create myfood_params
    @current_user.myfoods << myfood
    redirect_to recipes_path
  end

  def show
    @myfood = Myfood.find params[:id]
  end

  def remove_recipe
    myfood = Myfood.find params[:myfood_id]
    recipe = Recipe.find params[:recipe_id]
    myfood.recipes.destroy(recipe)
    redirect_to myfood
  end 

  def destroy
   @myfood = Myfood.find params[:id]
   @myfood.destroy
   redirect_to myfoods_path
  end

  private
  def myfood_params
    params.require(:myfood).permit(:title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController


  def new
    @recipe = Recipe.new
  end

  def search
    @recipes = Recipe.where("title LIKE ?", "%" + params[:q] + "%")
  end


  def create
    recipe = Recipe.create recipe_params
    redirect_to recipes_path  # show page
  end



  def index
    @recipes = Recipe.all
  end



  def show
    @recipe = Recipe.find params[:id]
  end



 def update
   recipe = Recipe.find params[:id]
   if params[:recipe][:myfood_ids].present?
     @myfood = Myfood.find params[:recipe][:myfood_ids]
     if @myfood.recipes.include? recipe
       redirect_to myfood_path(@myfood)
       flash[:alert] = "Recipe already exists."
     else
     @myfood.recipes << recipe
     redirect_to myfood_path(@myfood)
   end

   else
     recipe.update recipe_params
      redirect_to recipe_path(recipe)
   end
  end



 def edit
  @recipe = Recipe.find params[:id]
 end



 def destroy
  @recipe = Recipe.find params[:id]
  redirect_to recipes_path
 end



  private
    def recipe_params
      params.require(:recipe).permit(:title, :image, :course, :serves, :prep_time, :cook_time, :main_recipe, :video)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to recipes_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    before_action :check_for_admin, :only => [:index]

    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to recipes_path #you can redirect wherever you like.
      else
        render :new
      end
      end

      private
      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myfoods_helper.rb
module MyfoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myfoodlab</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

      <%= link_to '🍴 My Food Lab 🍳',  recipes_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <% if @current_user.present? %>
            <%= link_to 'New Recipe 🍳',  new_recipe_path, :class => "nav-link" %>
            <% end %>
          </li>

          <li class="nav-item active">
            <% if @current_user.present? %>
            <% if @current_user.admin? %>
            <%= link_to 'All users 👤', users_path, :class => "nav-link" %>
            <% end %>
          </li>

          <li class="nav-item active">
            <%= link_to 'Create Myfood List 📝', new_myfood_path, :class => "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to ' Myfood Lists 📝', myfoods_path, :class => "nav-link" %>
          </li>


          <li class="nav-item active">
            <%= link_to "Log out #{@current_user.email} 👤",  login_path, :class => "nav-link", :method => 'delete' %>
            <% else %>
            <%= link_to 'Sign up 👤',  new_user_path, :class => "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to 'Sign in 👤',  login_path, :class => "nav-link" %>
            <% end %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="/search">
          <input class="form-control mr-sm-2" name="q" type="search" placeholder="🔍" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>




  <div class="cont">
    <%= yield %>
  </div>
</body>
</html>

app/views/myfoods/index.html.erb
<h1>Myfood Lists 📝</h1>


<% @current_user.myfoods.each do |myfood| %>
<ul>
  <li>
<%= link_to myfood.title, myfood_path(myfood) %>
</li>
</ul>
<% end %>

app/views/myfoods/new.html.erb
<h1> Create New Myfood List 📝</h1>

<div class="list">
<%= form_for @myfood do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.submit %>
<% end %>
</div>

app/views/myfoods/show.html.erb
<h1> <%= @myfood.title %> 🍳</h1>

<% if flash[:alert].present? %>
 <%= flash[:alert]%>
<% end %>

<% @myfood.recipes.each do |recipe| %>
<ul>
  <li>
<%= link_to recipe.title, recipe_path(recipe) %>
<% if @current_user.present? %>
<%= link_to '❌', remove_recipe_path(@myfood.id, recipe.id), :method => 'delete' %>
 <% end %>
</li>
</ul>
<% end %>

app/views/pages/home.html.erb
  <h1> 🍴 WELCOME TO MY FOOD LAB 🍳</h1>
  <div class="homepage">
</div>

app/views/recipes/edit.html.erb
<h1>Edit recipe here!</h1>

<%= form_for @recipe do |f| %>
<ul>
 <div class="form-group">
<%= f.label :Title%>
<%= f.text_field :title, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :image%>
<%= f.text_field :image, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :Course%>
<%= f.text_field :course, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :serves%>
<%= f.number_field :serves, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :prep_time%>
<%= f.text_field :prep_time, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :cook_time%>
<%= f.text_field :cook_time, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :main_recipe%>
<%= f.text_field :main_recipe, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :video%>
<%= f.text_field :video, :class => 'form-control'%>
</div>

<%= f.submit "Edit Recipe", :class => "btn btn-outline-danger" %>

<% end %>

app/views/recipes/index.html.erb
<h1> 🍴 My Food Lab 🍳 </h1>

<div class="container">
<div class="row">


 <% @recipes.each do |recipe| %>
 <div class="col">
  <div class="card" style="width: 18rem;">
     <%= image_tag recipe.image, :class => 'card-img-top' if recipe.image.present? %>
     <div class="card-body">
       <h5 class="card-title"><%= recipe.title %></h5>
       <%= link_to '👁 View 👁', recipe_path(recipe.id), :class => 'btn-btn-primary' %>
     </div>
   </div>
   </div>
<% end %>


</div>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe 🍳</h1>

<%= form_for @recipe do |f| %>
<ul>
 <div class="form-group">
<%= f.label :Title%> 📝
<%= f.text_field :title, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :image%> 📸
<%= f.text_field :image, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :Course%> 🍽
<%= f.text_field :course, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :serves%> 👨‍👩‍👦
<%= f.number_field :serves, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :prep_time%> ⏱
<%= f.text_field :prep_time, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :cook_time%> ⏱
<%= f.text_field :cook_time, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :main_recipe%> 🍳
<%= f.text_field :main_recipe, :class => 'form-control'%>
</div>

<div class="form-group">
<%= f.label :video%> 🎥
<%= f.text_field :video, :class => 'form-control'%>
</div>

<%= f.submit "Create Recipe", :class => "btn btn-outline-danger" %>

<% end %>

app/views/recipes/search.html.erb
<h1>Search Results</h1>
<div class="container">
<div class="row">
<% @recipes.each do |recipe| %>
<div class="col">
 <div class="card" style="width: 18rem;">
    <%= image_tag recipe.image, :class => 'card-img-top' if recipe.image.present? %>
    <div class="card-body">
      <h5 class="card-title"><%= recipe.title %></h5>
      <%= link_to 'View Recipe', recipe_path(recipe.id), :class => 'btn-btn-primary' %>
    </div>
  </div>
  </div>
<% end %>
</div>
</div>

app/views/recipes/show.html.erb
<h1> <%= @recipe.title %></h1>

<div class="container">
<div class="row">

<%= image_tag @recipe.image, :class => 'feature' if @recipe.image.present? %>

<div class="info">
  <h5>Prep Time ⏱ : <%= @recipe.prep_time %> mins</h5>
  <h5>Cook Time ⏱ : <%= @recipe.cook_time %> mins</h5>
  <h5>Course Type 🍽 : <%= @recipe.course %></h5>
  <h5>Serves 👨‍👩‍👦 : <%= @recipe.serves %> persons</h5>
  </div>

</div>
</div>
<h3>Main Recipe 🍳 </h3>
  <div class="recipe">
   <%= @recipe.main_recipe %>
  </div>

<div class="video">
<h3>Youtube Video 🎥 </h3>
<%= @recipe.video.html_safe %>
</div>


<div class="addtolist">
<% if @current_user.present? %>
<%= form_for @recipe do |f| %>
<%= f.label :Myfood_lists %>
  <%= f.select :myfood_ids, @current_user.myfoods.pluck(:title, :id), :include_blank => true %>

  <%= f.submit "Add to list", :class=> "btn btn-info" %>
  <% end %>
  <% end %>
  </div>

  <% if @current_user.present? %>
  <% if @current_user.admin? %>
<h5> <%= link_to ('Edit Recipe'), edit_recipe_path(@recipe.id), :class=> "btn btn-success" %>
 <%= link_to 'Delete Recipe', recipe_path(@recipe), :method => 'delete', :class => "btn btn-outline-danger" %> </h5>
  <% end %>
  <% end %>

app/views/session/new.html.erb
<h1> Log In</h1>

<%= form_tag login_path do %>
<div class="form-group">
<%= label_tag :email %>
<%= email_field_tag :email, nil, :class => 'form-control'  %>
</div>

<div class="form-group">
<%= label_tag :password %>
<%= password_field_tag :password, nil, :class => 'form-control'  %>
</div>


<%= submit_tag 'Sign in', :class => "btn btn-outline-danger" %>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>


<div class="users"

<h3> We have <%= User.count %> current users. </h3>


<h4>
<% @users.each do |user| %>
<p> <%= user.email %> </p>
<% end %>
</h4>
</div>

app/views/users/new.html.erb
<h1>Sign Up 👤</h1>

<% if @user.errors.any? %>
<ol>
  <% @user.errors.full_messages.each do |msg| %>
  <li> <%= msg %></li>
  <% end %>
</ol>
<% end %>

<%= form_for @user do |f| %>
<div class="form-group">
<%= f.label :email  %> 📧
<%= f.email_field :email, :class => 'form-control' %>
</div>

<div class="form-group">
<%= f.label :password  %> 🔐
<%= f.password_field :password, :class => 'form-control' %>
</div>

<div class="form-group">
<%= f.label :password_confirmation  %> 🔐
<%= f.password_field :password_confirmation, :class => 'form-control' %>
</div>

<%= f.submit "Sign Up", :class => "btn btn-outline-danger" %>
<% end %>